### ISSUE TITLE
Links to publications

### ISSUE THREAD

**Issue by ramsafin** [DLuensch/StereoVision-ADCensus#11]
Hello, currently I am working on my masters thesis related to Visual SLAM.
Do you have any publications related to your project? It would be great if your thesis is publicly available (and in english). However, any publication would be good too, so I can reference to it in my work. Thanks for attention!

**Comment by DLuensch** [comment]
Hi @chupakabra1996 ,

we don't have plublished anything related with this project. Maybe the paper of the algorithm is helpfull for your master thesis. you can find it under Documents/ADCensus.pdf

Best regards,
Dennis

**Comment by ramsafin** [comment]
Thank you, @DLuensch!
