### ISSUE TITLE
Why not use cuda to run fast

### ISSUE THREAD

**Issue by luomomo** [DLuensch/StereoVision-ADCensus#12]
Since AD-census actually has superiority  GPU, this is the point of the paper.

**Comment by DLuensch** [comment]
> Since AD-census actually has superiority GPU, this is the point of the paper.

Hi luomomo,

this is true. This implementation was only a seminar paper during my study. Hence we didn't have the time to implement the algorithm with CUDA, but the current implementation is cpu multi threaded and works fine for common sized pictures.

**Comment by CaptainEven** [comment]
@DLuensch Hi, thanks for your excellent work! May i ask is AD-census you implemented multi-threading faster than SGBM in openCV?

**Comment by DLuensch** [comment]
@CaptainEven Hi, we never made any comparisons.
