### ISSUE TITLE
make ImageRectify

### ISSUE THREAD

**Issue by ghost** [DLuensch/StereoVision-ADCensus#4]
Hello, I can't make "ImageRectify" what's the issue - I very appreciate your help. Thanks.

pb@pb:~/work/StereoVision-ADCensus-master/ImageRectify/bin$ cmake ..
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Found Config++: /usr/lib/x86_64-linux-gnu/libconfig++.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/r59400/work/StereoVision-ADCensus-master/ImageRectify/bin
pb@pb:~/work/StereoVision-ADCensus-master/ImageRectify/bin$ make
Linking CXX executable ImageRectify
CMakeFiles/ImageRectify.dir/src/main.cpp.o: In function `main':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/main.cpp:151: undefined reference to`cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
CMakeFiles/ImageRectify.dir/src/main.cpp.o: In function `~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/main.cpp.o: In function `String':
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to`cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/main.cpp.o: In function `~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `String':
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to`cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadImages(std::vector<std::string, std::allocator<std::string> >, std::vector<cv::Mat, std::allocator<cv::Mat> >&)':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/rectify.cpp:218: undefined reference to`cv::imread(cv::String const&, int)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadImages(std::vector<std::string, std::allocator<std::string> >, std::vector<cv::Mat, std::allocator<cv::Mat> >&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `String':
/usr/local/include/opencv2/core/cvstd.hpp:625: undefined reference to`cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoExtrinsics(std::string, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect_<int>&)':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/rectify.cpp:134: undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`intrinsicExtrinsic::loadStereoExtrinsics(std::string, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect_<int>&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`String':
/usr/local/include/opencv2/core/cvstd.hpp:625: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`cv::internal::VecReaderProxy<int, 1>::operator()(std::vector<int, std::allocator<int> >&, unsigned long) const':
/usr/local/include/opencv2/core/persistence.hpp:812: undefined reference to `cv::FileNodeIterator::readRaw(cv::String const&, unsigned char*, unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`String':
/usr/local/include/opencv2/core/cvstd.hpp:625: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`cv::internal::VecReaderProxy<int, 1>::operator()(std::vector<int, std::allocator<int> >&, unsigned long) const':
/usr/local/include/opencv2/core/persistence.hpp:812: undefined reference to `cv::FileNodeIterator::readRaw(cv::String const&, unsigned char*, unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoExtrinsics(std::string, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect_<int>&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoExtrinsics(std::string, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Rect_<int>&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `String':
/usr/local/include/opencv2/core/cvstd.hpp:625: undefined reference to`cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoIntrinsics(std::string&, std::string&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/rectify.cpp:170: undefined reference to`cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoIntrinsics(std::string&, std::string&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `String':
/usr/local/include/opencv2/core/cvstd.hpp:625: undefined reference to`cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoIntrinsics(std::string&, std::string&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/rectify.cpp:171: undefined reference to`cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoIntrinsics(std::string&, std::string&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function `intrinsicExtrinsic::loadStereoIntrinsics(std::string&, std::string&, cv::Mat&, cv::Mat&, cv::Mat&, cv::Mat&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to`cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o:/usr/local/include/opencv2/core/cvstd.hpp:667: more undefined references to `cv::String::deallocate()' follow
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`intrinsicExtrinsic::loadImageList(std::string, std::vector<std::string, std::allocator<std::string> >&)':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/rectify.cpp:193: undefined reference to `cv::FileStorage::FileStorage(cv::String const&, int, cv::String const&)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`intrinsicExtrinsic::loadImageList(std::string, std::vector<std::string, std::allocator<std::string> >&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`intrinsicExtrinsic::loadImageList(std::string, std::vector<std::string, std::allocator<std::string> >&)':
/home/pb/work/StereoVision-ADCensus-master/ImageRectify/src/rectify.cpp:199: undefined reference to `cv::FileNode::type() const'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`String':
/usr/local/include/opencv2/core/cvstd.inl.hpp:81: undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`cv::FileNode::operator std::string() const':
/usr/local/include/opencv2/core/cvstd.inl.hpp:147: undefined reference to `cv::read(cv::FileNode const&, cv::String&, cv::String const&)'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`intrinsicExtrinsic::loadImageList(std::string, std::vector<std::string, std::allocator<std::string> >&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`~String':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
CMakeFiles/ImageRectify.dir/src/rectify.cpp.o: In function`intrinsicExtrinsic::loadImageList(std::string, std::vector<std::string, std::allocator<std::string> >&)':
/usr/local/include/opencv2/core/cvstd.hpp:667: undefined reference to `cv::String::deallocate()'
collect2: error: ld returned 1 exit status
make[2]: **\* [ImageRectify] Error 1
make[1]: **\* [CMakeFiles/ImageRectify.dir/all] Error 2
make: **\* [all] Error 2

**Comment by DLuensch** [comment]
Hi,

did you compile the opencv from source or was it installed from a
repository?

Best regards,
Dennis

2016-08-26 20:19 GMT+02:00 peter73421 notifications@github.com:

**Comment by ghost** [comment]
OpenCV (2.4.8) is installed via ubuntu 14.04 LTS "Synaptic manager". OpenCV
is not build from source. How your sw is compatible with OpenCV versions
(2.4 vs 3.1)?
